# Generated by Django 4.1.6 on 2023-04-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rusName', models.CharField(max_length=20)),
                ('latName', models.CharField(max_length=20)),
                ('sokr', models.CharField(max_length=20)),
                ('square', models.CharField(max_length=20)),
            ],
        ),
    ]
